<a href="https://colab.research.google.com/github/thomasshin/NLP_Study/blob/main/Pytorch_Practices/Pytorch_practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu118


# Tensor

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.shape

torch.Size([2])

In [7]:
# Matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
matrix.ndim

2

In [9]:
matrix.shape

torch.Size([2, 2])

In [10]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [11]:
tensor.shape

torch.Size([1, 3, 3])

In [12]:
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

# Random Tensor

In [13]:
random_tensor = torch.rand([1, 3, 4])
random_tensor

tensor([[[0.1302, 0.2162, 0.2363, 0.2903],
         [0.7372, 0.5887, 0.3884, 0.8897],
         [0.2852, 0.7961, 0.8354, 0.0096]]])

In [14]:
random_tensor.ndim

3

In [15]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224,224,3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#Zeros and ones

In [16]:
# Create a tensor of all zeros
zeros = torch.zeros([3, 4])
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
zeros.dtype

torch.float32

In [18]:
ones = torch.ones([3,4])
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
ones.dtype

torch.float32

#Creating a range of tensors and tensors-like

In [20]:
# Use torch.range()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#Tensor datatypes
**Note** Three issues with PyTorch and deep learning
1. Tensors not in the right shape
2. Tensors not in the right dtype
3. Tensors not on the right device


In [22]:
# Float 32 tensors
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what dtype is the tensor
                               device = None, # cpu, cuda(gpu)
                               requires_grad = False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype #default dtype = float32

torch.float32

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
ad = float_32_tensor * float_16_tensor
ad.dtype

torch.float32

In [26]:
int_32_tensor = torch.tensor([3,2,1], dtype = torch.long)
int_32_tensor

tensor([3, 2, 1])

In [27]:
float_32_tensor * int_32_tensor

tensor([ 9., 12.,  9.])

In [28]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0430, 0.4336, 0.7692, 0.0978],
        [0.6902, 0.2149, 0.3046, 0.3564],
        [0.6002, 0.4973, 0.8299, 0.0987]])

In [29]:
#info
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

torch.float32
torch.Size([3, 4])
cpu


#Tensor Operation
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix multiplication

In [30]:
# create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [31]:
tensor * 10

tensor([10, 20, 30])

In [32]:
tensor - 10

tensor([-9, -8, -7])

In [33]:
#pytorch in-built function
torch.add(tensor, 14)

tensor([15, 16, 17])

In [34]:
torch.mul(tensor, 5)

tensor([ 5, 10, 15])

#Matrix multiplication
1. Element-wise
2. Matrix multiplication

In [35]:
# element-wise multiplication
print(tensor)
print(tensor * tensor)

tensor([1, 2, 3])
tensor([1, 4, 9])


In [36]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [37]:
tensor = [3,6,9]
mat = 0
for i in range(len(tensor)):
  mat += tensor[i] * tensor[i]
mat

126

##shape errors

In [40]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [41]:
torch.matmul(tensor_A.T, tensor_B)

tensor([[ 89,  98],
        [116, 128]])

min, max, mean, sum, etc

In [42]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [43]:
# min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [44]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [45]:
torch.mean(x.type(torch.float32)) #not the right dtype

tensor(45.)

In [46]:
torch.sum(x)

tensor(450)

#finding positional min and max
argmin, argmax

In [47]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
x.argmin()

tensor(0)

In [49]:
x.argmax()

tensor(9)

#Reshaping, Stacking, Squeezing, Unsqueezing

In [50]:
y = torch.arange(1, 11)
y, y.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [51]:
y_reshape = y.reshape(2, 5)
y_reshape, y_reshape.shape

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 torch.Size([2, 5]))

In [52]:
#change the view
z = y.view(5,2)
z, y

(tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [53]:
#changing z changes y (view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z, y

(tensor([[ 5,  2],
         [ 5,  4],
         [ 5,  6],
         [ 5,  8],
         [ 5, 10]]),
 tensor([ 5,  2,  5,  4,  5,  6,  5,  8,  5, 10]))

In [54]:
#stack tensor on top of each other
y_stack = torch.stack([y,y], dim=0)
y_stack

tensor([[ 5,  2,  5,  4,  5,  6,  5,  8,  5, 10],
        [ 5,  2,  5,  4,  5,  6,  5,  8,  5, 10]])

In [55]:
#squeeze - remove all single dimensions from a target tensor
c_reshape = y.reshape(-1, 10)
c_reshape

tensor([[ 5,  2,  5,  4,  5,  6,  5,  8,  5, 10]])

In [56]:
c_reshape.squeeze(), c_reshape.squeeze().shape

(tensor([ 5,  2,  5,  4,  5,  6,  5,  8,  5, 10]), torch.Size([10]))

In [57]:
#unsqueeze - add an extra dimension with unsqueeze
c_reshape.squeeze().unsqueeze(dim=1)

tensor([[ 5],
        [ 2],
        [ 5],
        [ 4],
        [ 5],
        [ 6],
        [ 5],
        [ 8],
        [ 5],
        [10]])

In [58]:
#torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2,0,1)
x_permuted.shape


torch.Size([3, 224, 224])

#Indexing

In [59]:
x = torch.tensor([[[1,2,3],
                   [4,5,6],
                   [7,8,9]]])

In [60]:
#9
x[0,2,2]
#3,6,9
x[0,:,2]

tensor([3, 6, 9])

#Pytorch and Numpy
np to torch : torch.from_numpy(ndarray)

torch to np : torch.tensor.numpy()

In [61]:
import numpy as np
array = np.array([1,2,3,4,5])
tensor = torch.from_numpy(array).type(torch.float32) #warning: when converting from np to torch, default dtype is float64(which is that of np), so need to convert it back to float32
array, tensor

(array([1, 2, 3, 4, 5]), tensor([1., 2., 3., 4., 5.]))

In [62]:
array += 1
array, tensor

(array([2, 3, 4, 5, 6]), tensor([1., 2., 3., 4., 5.]))

In [63]:
#tensor to numpy array
tensor2 = torch.tensor([1,2,3,4,5])
tensor1 = tensor2.numpy()
tensor1, tensor2

(array([1, 2, 3, 4, 5]), tensor([1, 2, 3, 4, 5]))

In [64]:
tensor2 += 1
tensor1, tensor2

(array([2, 3, 4, 5, 6]), tensor([2, 3, 4, 5, 6]))

In [65]:
tensor = torch.ones(5)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [66]:
tensor += 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

#Reproducibility
random seed

In [67]:
torch.rand(3,3)

tensor([[0.2664, 0.8978, 0.1873],
        [0.0740, 0.2861, 0.8677],
        [0.3801, 0.5418, 0.8359]])

In [68]:
random_seed = 42

torch.manual_seed(random_seed)
random_tensor_c = torch.rand(3,3)

torch.manual_seed(random_seed)
random_tensor_d = torch.rand(3,3)
print(random_tensor_c == random_tensor_d)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


#Running Tensors and Pytorch objects on the GPUs (faster computations)
GPU = faster computation on numbers thanks to CUDA + NVIDIA Hardware + PyTorch working behind the scenes.

Getting a GPU
1. Google Colab (free GPU)
2. Purchase GPU
3. Use cloud computing such as GCP, Azure, AWS...

In [69]:
!nvidia-smi

Wed Oct 25 03:50:25 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8     8W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

#2. Check for GPU access with PyTorch


In [70]:
#Check for GPU access with pytorch
torch.cuda.is_available()

True

In [71]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [72]:
#Count number of devices
torch.cuda.device_count()

1